import uuid
from datetime import date,datetime
from decimal import Decimal
from enum import Enum
from typing import Optional
from sqlalchemy import JSON,Column,Numeric,Text
from sqlmodel import Field,SQLModel,UniqueConstraint
from app.core.db_types import EnumString
class CatalogEntityTypeEnum(str,Enum):PRODUCT="PRODUCT";CATEGORY="CATEGORY";MODIFIER="MODIFIER";OPTION="OPTION"
class PublicationStatusEnum(str,Enum):PENDING="PENDING";PROCESSING="PROCESSING";PARTIAL="PARTIAL";SUCCEEDED="SUCCEEDED";FAILED="FAILED"
class PublicationItemStatusEnum(str,Enum):PENDING="PENDING";SUCCEEDED="SUCCEEDED";FAILED="FAILED"
class SettlementStatusEnum(str,Enum):PENDING="PENDING";PARTIAL="PARTIAL";PAID="PAID";DIVERGENT="DIVERGENT"
class ChannelCatalogMapping(SQLModel,table=True):
 __tablename__="channel_catalog_mappings";__table_args__=(UniqueConstraint("merchant_connection_id","entity_type","internal_id",name="uq_channel_internal_catalog_mapping"),UniqueConstraint("merchant_connection_id","entity_type","external_id",name="uq_channel_external_catalog_mapping"))
 id:uuid.UUID=Field(default_factory=uuid.uuid4,primary_key=True);tenant_id:uuid.UUID=Field(foreign_key="tenants.id",index=True);store_id:uuid.UUID=Field(foreign_key="stores.id",index=True);merchant_connection_id:uuid.UUID=Field(foreign_key="merchant_connections.id",index=True)
 entity_type:CatalogEntityTypeEnum=Field(sa_column=Column(EnumString(CatalogEntityTypeEnum),nullable=False,index=True));internal_id:uuid.UUID=Field(index=True);external_id:str=Field(max_length=200,index=True);created_at:datetime=Field(default_factory=datetime.utcnow,index=True);updated_at:datetime=Field(default_factory=datetime.utcnow)
class ChannelCatalogOffer(SQLModel,table=True):
 __tablename__="channel_catalog_offers";__table_args__=(UniqueConstraint("merchant_connection_id","product_id",name="uq_channel_product_offer"),)
 id:uuid.UUID=Field(default_factory=uuid.uuid4,primary_key=True);tenant_id:uuid.UUID=Field(foreign_key="tenants.id",index=True);store_id:uuid.UUID=Field(foreign_key="stores.id",index=True);merchant_connection_id:uuid.UUID=Field(foreign_key="merchant_connections.id",index=True);product_id:uuid.UUID=Field(foreign_key="products.id",index=True)
 price:Decimal=Field(sa_column=Column(Numeric(14,4),nullable=False));available:bool=Field(default=True,index=True);stock_quantity:Optional[Decimal]=Field(default=None,sa_column=Column(Numeric(14,4)));desired_version:int=Field(default=1,ge=1);published_version:int=Field(default=0,ge=0);last_publication_status:PublicationItemStatusEnum=Field(default=PublicationItemStatusEnum.PENDING,sa_column=Column(EnumString(PublicationItemStatusEnum),nullable=False,index=True));created_at:datetime=Field(default_factory=datetime.utcnow);updated_at:datetime=Field(default_factory=datetime.utcnow)
class ChannelPublicationBatch(SQLModel,table=True):
 __tablename__="channel_publication_batches";__table_args__=(UniqueConstraint("tenant_id","idempotency_key",name="uq_tenant_channel_publication_key"),)
 id:uuid.UUID=Field(default_factory=uuid.uuid4,primary_key=True);tenant_id:uuid.UUID=Field(foreign_key="tenants.id",index=True);store_id:uuid.UUID=Field(foreign_key="stores.id",index=True);merchant_connection_id:uuid.UUID=Field(foreign_key="merchant_connections.id",index=True);status:PublicationStatusEnum=Field(default=PublicationStatusEnum.PENDING,sa_column=Column(EnumString(PublicationStatusEnum),nullable=False,index=True));idempotency_key:str=Field(max_length=160,index=True);request_hash:str=Field(max_length=64);created_by:uuid.UUID=Field(index=True);created_at:datetime=Field(default_factory=datetime.utcnow,index=True);updated_at:datetime=Field(default_factory=datetime.utcnow)
class ChannelPublicationItem(SQLModel,table=True):
 __tablename__="channel_publication_items";__table_args__=(UniqueConstraint("batch_id","offer_id",name="uq_publication_batch_offer"),)
 id:uuid.UUID=Field(default_factory=uuid.uuid4,primary_key=True);tenant_id:uuid.UUID=Field(foreign_key="tenants.id",index=True);batch_id:uuid.UUID=Field(foreign_key="channel_publication_batches.id",ondelete="CASCADE",index=True);offer_id:uuid.UUID=Field(foreign_key="channel_catalog_offers.id",index=True);desired_version:int;provider_operation_key:str=Field(max_length=200,index=True);status:PublicationItemStatusEnum=Field(default=PublicationItemStatusEnum.PENDING,sa_column=Column(EnumString(PublicationItemStatusEnum),nullable=False,index=True));attempt_count:int=Field(default=0);provider_result_ref:Optional[str]=Field(default=None,max_length=200);error_code:Optional[str]=Field(default=None,max_length=80);error_message:Optional[str]=Field(default=None,sa_column=Column(Text));created_at:datetime=Field(default_factory=datetime.utcnow,index=True);updated_at:datetime=Field(default_factory=datetime.utcnow)
class MarketplaceSettlement(SQLModel,table=True):
 __tablename__="marketplace_settlements";__table_args__=(UniqueConstraint("merchant_connection_id","provider_document_ref",name="uq_connection_settlement_document"),UniqueConstraint("tenant_id","idempotency_key",name="uq_tenant_settlement_key"))
 id:uuid.UUID=Field(default_factory=uuid.uuid4,primary_key=True);tenant_id:uuid.UUID=Field(foreign_key="tenants.id",index=True);store_id:uuid.UUID=Field(foreign_key="stores.id",index=True);merchant_connection_id:uuid.UUID=Field(foreign_key="merchant_connections.id",index=True);provider_document_ref:str=Field(max_length=200,index=True);external_order_id:Optional[str]=Field(default=None,max_length=160,index=True);order_id:Optional[uuid.UUID]=Field(default=None,foreign_key="orders.id",index=True);competence_date:date=Field(index=True)
 gross_amount:Decimal=Field(sa_column=Column(Numeric(14,4),nullable=False));commission_amount:Decimal=Field(sa_column=Column(Numeric(14,4),nullable=False));fee_amount:Decimal=Field(sa_column=Column(Numeric(14,4),nullable=False));promotion_amount:Decimal=Field(sa_column=Column(Numeric(14,4),nullable=False));adjustment_amount:Decimal=Field(sa_column=Column(Numeric(14,4),nullable=False));expected_net_amount:Decimal=Field(sa_column=Column(Numeric(14,4),nullable=False));paid_amount:Decimal=Field(default=Decimal("0"),sa_column=Column(Numeric(14,4),nullable=False));status:SettlementStatusEnum=Field(default=SettlementStatusEnum.PENDING,sa_column=Column(EnumString(SettlementStatusEnum),nullable=False,index=True));idempotency_key:str=Field(max_length=160,index=True);request_hash:str=Field(max_length=64);created_by:uuid.UUID=Field(index=True);created_at:datetime=Field(default_factory=datetime.utcnow,index=True);updated_at:datetime=Field(default_factory=datetime.utcnow)
class MarketplaceSettlementPayment(SQLModel,table=True):
 __tablename__="marketplace_settlement_payments";__table_args__=(UniqueConstraint("settlement_id","provider_payment_ref",name="uq_settlement_provider_payment"),)
 id:uuid.UUID=Field(default_factory=uuid.uuid4,primary_key=True);tenant_id:uuid.UUID=Field(foreign_key="tenants.id",index=True);settlement_id:uuid.UUID=Field(foreign_key="marketplace_settlements.id",ondelete="CASCADE",index=True);provider_payment_ref:str=Field(max_length=200,index=True);amount:Decimal=Field(sa_column=Column(Numeric(14,4),nullable=False));paid_at:datetime;created_at:datetime=Field(default_factory=datetime.utcnow,index=True)
