"""S13 channel catalog and marketplace reconciliation.
Revision ID: 028_channel_catalog
Revises: 027_transfer_lineage
"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='028_channel_catalog';down_revision='027_transfer_lineage';branch_labels=None;depends_on=None
def idx(t,cs):
 for c in cs:op.create_index(f'ix_{t}_{c}',t,[c])
def upgrade():
 u=postgresql.UUID(as_uuid=True);now=datetime.utcnow()
 op.create_table('channel_catalog_mappings',sa.Column('id',u,primary_key=True),sa.Column('tenant_id',u,sa.ForeignKey('tenants.id'),nullable=False),sa.Column('store_id',u,sa.ForeignKey('stores.id'),nullable=False),sa.Column('merchant_connection_id',u,sa.ForeignKey('merchant_connections.id'),nullable=False),sa.Column('entity_type',sa.String(50),nullable=False),sa.Column('internal_id',u,nullable=False),sa.Column('external_id',sa.String(200),nullable=False),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('updated_at',sa.DateTime(),nullable=False),sa.UniqueConstraint('merchant_connection_id','entity_type','internal_id',name='uq_channel_internal_catalog_mapping'),sa.UniqueConstraint('merchant_connection_id','entity_type','external_id',name='uq_channel_external_catalog_mapping'));idx('channel_catalog_mappings',('tenant_id','store_id','merchant_connection_id','entity_type','internal_id','external_id','created_at'))
 op.create_table('channel_catalog_offers',sa.Column('id',u,primary_key=True),sa.Column('tenant_id',u,sa.ForeignKey('tenants.id'),nullable=False),sa.Column('store_id',u,sa.ForeignKey('stores.id'),nullable=False),sa.Column('merchant_connection_id',u,sa.ForeignKey('merchant_connections.id'),nullable=False),sa.Column('product_id',u,sa.ForeignKey('products.id'),nullable=False),sa.Column('price',sa.Numeric(14,4),nullable=False),sa.Column('available',sa.Boolean(),nullable=False),sa.Column('stock_quantity',sa.Numeric(14,4)),sa.Column('desired_version',sa.Integer(),nullable=False),sa.Column('published_version',sa.Integer(),nullable=False),sa.Column('last_publication_status',sa.String(50),nullable=False),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('updated_at',sa.DateTime(),nullable=False),sa.UniqueConstraint('merchant_connection_id','product_id',name='uq_channel_product_offer'));idx('channel_catalog_offers',('tenant_id','store_id','merchant_connection_id','product_id','available','last_publication_status'))
 op.create_table('channel_publication_batches',sa.Column('id',u,primary_key=True),sa.Column('tenant_id',u,sa.ForeignKey('tenants.id'),nullable=False),sa.Column('store_id',u,sa.ForeignKey('stores.id'),nullable=False),sa.Column('merchant_connection_id',u,sa.ForeignKey('merchant_connections.id'),nullable=False),sa.Column('status',sa.String(50),nullable=False),sa.Column('idempotency_key',sa.String(160),nullable=False),sa.Column('request_hash',sa.String(64),nullable=False),sa.Column('created_by',u,nullable=False),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('updated_at',sa.DateTime(),nullable=False),sa.UniqueConstraint('tenant_id','idempotency_key',name='uq_tenant_channel_publication_key'));idx('channel_publication_batches',('tenant_id','store_id','merchant_connection_id','status','idempotency_key','created_by','created_at'))
 op.create_table('channel_publication_items',sa.Column('id',u,primary_key=True),sa.Column('tenant_id',u,sa.ForeignKey('tenants.id'),nullable=False),sa.Column('batch_id',u,sa.ForeignKey('channel_publication_batches.id',ondelete='CASCADE'),nullable=False),sa.Column('offer_id',u,sa.ForeignKey('channel_catalog_offers.id'),nullable=False),sa.Column('desired_version',sa.Integer(),nullable=False),sa.Column('provider_operation_key',sa.String(200),nullable=False),sa.Column('status',sa.String(50),nullable=False),sa.Column('attempt_count',sa.Integer(),nullable=False),sa.Column('provider_result_ref',sa.String(200)),sa.Column('error_code',sa.String(80)),sa.Column('error_message',sa.Text()),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('updated_at',sa.DateTime(),nullable=False),sa.UniqueConstraint('batch_id','offer_id',name='uq_publication_batch_offer'));idx('channel_publication_items',('tenant_id','batch_id','offer_id','provider_operation_key','status','created_at'))
 op.create_table('marketplace_settlements',sa.Column('id',u,primary_key=True),sa.Column('tenant_id',u,sa.ForeignKey('tenants.id'),nullable=False),sa.Column('store_id',u,sa.ForeignKey('stores.id'),nullable=False),sa.Column('merchant_connection_id',u,sa.ForeignKey('merchant_connections.id'),nullable=False),sa.Column('provider_document_ref',sa.String(200),nullable=False),sa.Column('external_order_id',sa.String(160)),sa.Column('order_id',u,sa.ForeignKey('orders.id')),sa.Column('competence_date',sa.Date(),nullable=False),sa.Column('gross_amount',sa.Numeric(14,4),nullable=False),sa.Column('commission_amount',sa.Numeric(14,4),nullable=False),sa.Column('fee_amount',sa.Numeric(14,4),nullable=False),sa.Column('promotion_amount',sa.Numeric(14,4),nullable=False),sa.Column('adjustment_amount',sa.Numeric(14,4),nullable=False),sa.Column('expected_net_amount',sa.Numeric(14,4),nullable=False),sa.Column('paid_amount',sa.Numeric(14,4),nullable=False),sa.Column('status',sa.String(50),nullable=False),sa.Column('idempotency_key',sa.String(160),nullable=False),sa.Column('request_hash',sa.String(64),nullable=False),sa.Column('created_by',u,nullable=False),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('updated_at',sa.DateTime(),nullable=False),sa.UniqueConstraint('merchant_connection_id','provider_document_ref',name='uq_connection_settlement_document'),sa.UniqueConstraint('tenant_id','idempotency_key',name='uq_tenant_settlement_key'));idx('marketplace_settlements',('tenant_id','store_id','merchant_connection_id','provider_document_ref','external_order_id','order_id','competence_date','status','idempotency_key','created_by','created_at'))
 op.create_table('marketplace_settlement_payments',sa.Column('id',u,primary_key=True),sa.Column('tenant_id',u,sa.ForeignKey('tenants.id'),nullable=False),sa.Column('settlement_id',u,sa.ForeignKey('marketplace_settlements.id',ondelete='CASCADE'),nullable=False),sa.Column('provider_payment_ref',sa.String(200),nullable=False),sa.Column('amount',sa.Numeric(14,4),nullable=False),sa.Column('paid_at',sa.DateTime(),nullable=False),sa.Column('created_at',sa.DateTime(),nullable=False),sa.UniqueConstraint('settlement_id','provider_payment_ref',name='uq_settlement_provider_payment'));idx('marketplace_settlement_payments',('tenant_id','settlement_id','provider_payment_ref','created_at'))
 p=sa.table('permissions',sa.column('key',sa.String),sa.column('name',sa.String),sa.column('description',sa.Text),sa.column('capability_key',sa.String),sa.column('created_at',sa.DateTime));rows=(('channel.catalog.read','Consultar catálogo por canal'),('channel.catalog.manage','Gerenciar catálogo por canal'),('channel.settlement.manage','Conciliar repasses de marketplace'));op.bulk_insert(p,[{'key':k,'name':n,'description':n,'capability_key':'delivery_orders','created_at':now}for k,n in rows]);op.execute(sa.text("INSERT INTO role_profile_permissions(id,role_profile_id,permission_key) SELECT gen_random_uuid(),rp.id,p.key FROM role_profiles rp CROSS JOIN permissions p WHERE rp.is_system=true AND p.key IN('channel.catalog.read','channel.catalog.manage','channel.settlement.manage') AND rp.code IN('OWNER','TENANT_OWNER','ADMIN','MANAGER')"))
 platform="current_setting('app.platform_access',true)='true'";tenant="tenant_id=nullif(current_setting('app.tenant_id',true),'')::uuid";store="store_id=nullif(current_setting('app.store_id',true),'')::uuid"
 for t in ('channel_catalog_mappings','channel_catalog_offers','channel_publication_batches','marketplace_settlements'):
  op.execute(f'ALTER TABLE {t} ENABLE ROW LEVEL SECURITY');op.execute(f'ALTER TABLE {t} FORCE ROW LEVEL SECURITY');e=f'({platform}) OR (({tenant}) AND (nullif(current_setting(\'app.store_id\',true),\'\') IS NULL OR {store}))';op.execute(f'CREATE POLICY {t}_isolation ON {t} FOR ALL USING ({e}) WITH CHECK ({e})')
 for t in ('channel_publication_items','marketplace_settlement_payments'):
  op.execute(f'ALTER TABLE {t} ENABLE ROW LEVEL SECURITY');op.execute(f'ALTER TABLE {t} FORCE ROW LEVEL SECURITY');e=f'({platform}) OR ({tenant})';op.execute(f'CREATE POLICY {t}_isolation ON {t} FOR ALL USING ({e}) WITH CHECK ({e})')
def downgrade():
 op.execute("DELETE FROM role_profile_permissions WHERE permission_key LIKE 'channel.catalog.%' OR permission_key LIKE 'channel.settlement.%'");op.execute("DELETE FROM permissions WHERE key LIKE 'channel.catalog.%' OR key LIKE 'channel.settlement.%'")
 for t in ('marketplace_settlement_payments','marketplace_settlements','channel_publication_items','channel_publication_batches','channel_catalog_offers','channel_catalog_mappings'):op.drop_table(t)
