import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const source = (path: string) => readFile(new URL(path, import.meta.url), 'utf8')

test('gives the Owner a real commercial plan catalog before tenant contracting', async () => {
  const shell = await source('../src/components/owner/OwnerConsoleShell.tsx')
  const plans = await source('../src/components/owner/ServicePlansView.tsx')
  const workspace = await source('../src/components/owner/TenantWorkspace.tsx')
  const provisioning = await source('../src/components/owner/CreateTenantPanel.tsx')
  const api = await source('../src/services/api.ts')

  assert.match(shell, /label="Planos comerciais"/)
  assert.match(shell, /fetchServicePlans\(\)/)
  assert.match(shell, /Verificando…/)
  assert.match(plans, /Nenhum plano comercial cadastrado/)
  assert.match(plans, /Cadastrar primeiro plano/)
  assert.match(plans, /Vincular a uma organização/)
  assert.match(plans, /Salvando…/)
  assert.match(plans, /referência contratual sem medição/)
  assert.match(workspace, /Modelos de negócio/)
  assert.match(workspace, /Capabilities do cliente/)
  assert.match(workspace, /Quotas vigentes/)
  assert.match(workspace, /capabilities ·/)
  assert.match(workspace, /Gerenciar capabilities/)
  assert.match(workspace, /Organizações → cliente → Contrato → Capabilities/)
  assert.match(workspace, /setUsers\(plan\.user_limit == null \? ''/)
  assert.match(workspace, /detail\.contract\?\.capability_keys/)
  assert.match(workspace, /Cadastre um plano comercial ativo/)
  assert.match(workspace, /Ir para Planos comerciais/)
  assert.match(provisioning, /NumberField id="billingDay" label="Dia de vencimento"/)
  assert.match(provisioning, /billing_day: Number\(form\.billingDay\)/)
  assert.match(provisioning, /billingDay: ''/)
  assert.match(provisioning, /users: plan\.user_limit == null \? current\.users/)
  assert.doesNotMatch(provisioning, /Todo dia 1/)
  assert.doesNotMatch(workspace, /if \(editing && selectablePlans\.length === 0\) return/)
  assert.match(api, /createServicePlan/)
  assert.match(api, /updateServicePlan/)
  assert.match(api, /method: 'PUT'/)
})
