import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const source = (path: string) => readFile(new URL(path, import.meta.url), 'utf8')

test('exposes real SaaS invoicing without tenant operating data or fake financial states', async () => {
  const shell = await source('../src/components/owner/OwnerConsoleShell.tsx')
  const finance = await source('../src/components/owner/FinanceSaasView.tsx')
  const workspace = await source('../src/components/owner/TenantWorkspace.tsx')
  const api = await source('../src/services/api.ts')

  assert.match(shell, /label="Financeiro SaaS"/)
  assert.match(finance, /fetchPlatformFinanceOverview/)
  assert.match(finance, /fetchSaasInvoices/)
  assert.match(finance, /generateSaasInvoices/)
  assert.match(finance, /issueSaasInvoice/)
  assert.match(finance, /voidSaasInvoice/)
  assert.match(finance, /fetchSaasPayments/)
  assert.match(finance, /recordManualSaasPayment/)
  assert.match(finance, /refundSaasPayment/)
  assert.match(finance, /markSaasInvoicesOverdue/)
  assert.match(finance, /Exportar CSV/)
  assert.match(finance, /ledger financeiro SaaS persistido/)
  assert.match(finance, /Recebimentos e cobrança/)
  assert.match(finance, /Saldo vencido/)
  assert.match(finance, /fetchLatestSaasFinanceProjection/)
  assert.match(finance, /rebuildSaasFinanceProjection/)
  assert.match(finance, /Ainda não existe assinatura SaaS persistida/)
  assert.match(finance, /Aguardando base contratual/)
  assert.match(finance, /Regularizar organizações/)
  assert.match(finance, /working \|\| !competence \|\| !hasSubscriptions/)
  assert.match(finance, /Sem baseline anterior/)
  assert.match(finance, /formula_version/)
  assert.match(finance, /watermark/)
  assert.match(finance, /source_fingerprint/)
  assert.doesNotMatch(finance, /MRR, ARR e churn históricos/)
  assert.doesNotMatch(finance, /overview\?\.overdue_subscriptions/)
  assert.doesNotMatch(finance, /billing_status/)
  assert.doesNotMatch(finance, /const mock|fixture|Math\.random/i)

  assert.match(api, /platform\/finance\/overview/)
  assert.match(api, /platform\/finance\/billing-accounts/)
  assert.match(api, /control\/finance\/invoices/)
  assert.match(api, /control\/finance\/payments/)
  assert.match(api, /control\/finance\/collections\/mark-overdue/)
  assert.match(api, /control\/finance\/projections\/latest/)
  assert.match(api, /control\/finance\/projections\/rebuild/)
  assert.match(api, /Idempotency-Key/)
  assert.match(workspace, /Conta de cobrança/)
  assert.match(workspace, /Financeiro bloqueado/)
  assert.match(workspace, /Não configurada/)
  assert.match(workspace, /Abrir Financeiro SaaS/)
  assert.match(workspace, /Vencimento todo dia 1/)
  assert.match(workspace, /A data é calculada automaticamente em cada competência/)
  assert.match(workspace, /CurrencyInput label="Valor-base contratado"/)
  assert.doesNotMatch(workspace, /Próxima cobrança contratual prevista/)
  assert.match(workspace, /onClick=\{\(\) => setTab\('administrator'\)\}/)
  assert.match(workspace, /expected_version: account\?\.version \?\? 0/)
  assert.match(workspace, /Não contém faturamento, caixa, vendas ou lucro do tenant/)
  assert.doesNotMatch(workspace, /ainda não existem como fatos financeiros/)
  assert.doesNotMatch(workspace, /permanece em implementação/)

  for (const forbidden of ['vendas do tenant', 'caixas abertos', 'lucro do tenant']) {
    assert.doesNotMatch(finance.toLowerCase(), new RegExp(forbidden))
  }
})
